apiVersion: apps/v1
kind: Deployment
metadata:
  name:  aburaihan-dev
  namespace: demo
spec:
  selector:
    matchLabels:
      app: aburaihan-dev
  template:
    metadata:
      labels:
        app: aburaihan-dev
    spec:
      containers:
        - name: aburaihan-dev
          image: msrabon/scrum-dhaka-2023:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000