apiVersion: v1
kind: Service
metadata:
  name:  aburaihan-dev
  namespace: demo
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: aburaihan-dev